### ISSUE TITLE
No changes in inspector, Unity 5.6.3p2

### ISSUE THREAD

**Issue by sleepandpancakes** [SubjectNerd-Unity/ReorderableInspector#3]
No changes to the default inspector are made when using the [Reorderable] and [EditScriptable] attributes in Unity 5.6.3p2. No compiler errors are given, but the default arrays are drawn and inline editing of Scriptable objects are not enabled.

<img width="200" alt="screen shot 2017-12-02 at 9 36 05 am" src="https://user-images.githubusercontent.com/6812571/33672773-acceea6a-da70-11e7-8af3-f3098603231f.png">
<img width="200" alt="screen shot 2017-12-02 at 9 36 16 am" src="https://user-images.githubusercontent.com/6812571/33672769-ab18e5ae-da70-11e7-9e17-b6c898396ac2.png">

**Comment by sleepandpancakes** [comment]
I updated to Unity 2017.3.1 and this issue persists.

**Comment by Nomy1** [comment]
Same, nothing changes.

**Comment by ChemiKhazi** [comment]
Are there any other plugins being used in the project? I'm unable to reproduce in 5.6.5f1 and 2017.2.0f3

I'm going to try with the specific reported versions but it takes me a while to download.

**Comment by sleepandpancakes** [comment]
I tried testing it in an empty project in 2017.3.1 and it still does nothing. Is it possibly a platform issue? I am using Mac

**Comment by sleepandpancakes** [comment]
FYI, I just tried it on 2017.3.1 on Windows and it works. Seems like it may be related to the platform

**Comment by ChemiKhazi** [comment]
Hmm. I'm not aware of platform specific code. This might be tricky for me to fix since I don't have access to mac machines.

**Comment by manotone** [comment]
If it makes you feel any better I'm on windows 8 and can't get this to work, so it may not be platform specific. Having the same problem with the inspector not changing. Using Unity 2017.2.0f3

**Comment by FirstGearGames** [comment]
Also doesn't work on Unity 2017.4.2f2.

**Comment by FirstGearGames** [comment]
Got mine working fine in 2017.4.2f2. I was even able to move them into custom folders. Just make sure you maintain the "Editor" folder or else Unity won't recognize that portion as an editor script.

**Comment by sleepandpancakes** [comment]
yeah I don't think this is platform specific. Doesn't work on Unity 2018 for me in either Windows or Mac. The editor scripts are in the Editor folder

**Comment by Naphier** [comment]
I just implemented in a project using Unity 2018.2 on Win 10. Works like a charm.

**Comment by sleepandpancakes** [comment]
Yeah this plugin now works for me, on both Mac and Windows. I think the culprit may have been a different editor plugin (that I've since deleted) that was interfering with this one somehow. If other people are still having the same issue I recommend making sure that it's not caused by a different plugin. Thanks for the awesome and very useful extension.
